import type { Metadata } from "next";

import { Inter } from "next/font/google";

import { Header } from "@/components/Header";

import "./globals.css";
import StoreProvider from "./StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Just Travel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreProvider>
          <body className={inter.className}>
              <Header/>
              <div className="container">
                {children}
              </div>
          </body>
      </StoreProvider>
    </html>
  );
}
